/**
 * Registers the official v1 API surface for Nexus backend clients.
 * Legacy `/api/*` routes stay active while clients migrate to `/api/v1/*`.
 */
import { Router } from 'express';
import adminAgentsRoutes from './admin-agents.routes';
import adminRoutes from './admin.routes';
import adminSeoRoutes from './admin-seo.routes';
import adminTenantsRoutes from './admin-tenants.routes';
import adminTenantBrandingRoutes from './admin-tenant-branding.routes';
import adminOffersRoutes from './admin-offers.routes';
import adminBusinessSetupApprovalsRoutes from './admin.business-setup-approvals.routes';
import adminOrganizationsRoutes from './admin-organizations.routes';
import adminUsersRoutes from './admin.users.routes';
import agentApprovalsRoutes from './agent-approvals.routes';
import analyticsRoutes from './analytics.routes';
import authRoutes from './auth.routes';
import phoneOtpRoutes from './phone-otp.routes';
import emailOtpRoutes from './email-otp.routes';
import googleWalletRoutes from './google-wallet.routes';
import walletProfileRoutes from './wallet-profile.routes';
import walletTenantsRoutes, { tenantJoinAdminRouter } from './wallet-tenants.routes';
import walletPhoneRoutes from './wallet-phone.routes';
import walletDevRoutes from './wallet-dev.routes';
import tenantLogoRoutes from './tenant-logo.routes';
import blogRoutes from './blog.routes';
import chatRoutes from './chat.routes';
import contactSalesRoutes from './contact-sales.routes';
import dashboardRoutes from './dashboard.routes';
import domainContactsRoutes from './domain-contacts.routes';
import domainContactFieldsRoutes from './domain-contact-fields.routes';
import domainMemberActionsRoutes from './domain-member-actions.routes';
import domainMemberInvitationsRoutes from './domain-member-invitations.routes';
import domainTenantRoutes from './domain-tenant.routes';
import invitesRoutes from './invites.routes';
import leadsRoutes from './leads.routes';
import onboardingRoutes from './onboarding.routes';
import onboardingPhoneOtpRoutes from './onboarding-phone-otp.routes';
import orgsRoutes from './orgs.routes';
import partnersRoutes from './partners.route';
import paymentsRoutes from './payments.routes';
import publicRoutes from './public.routes';
import offersRoutes from './offers.routes';
import purchaseRoutes from './purchase.routes';
import pushRoutes from './push.routes';
import seoRoutes from './seo.routes';
import userRoutes from './user.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/auth/phone', phoneOtpRoutes);
router.use('/auth/email-otp', emailOtpRoutes);
router.use('/auth/google/wallet', googleWalletRoutes);
router.use('/wallet', walletProfileRoutes);
router.use('/wallet', walletTenantsRoutes);
router.use('/wallet', walletPhoneRoutes);
router.use('/wallet/dev', walletDevRoutes);
router.use('/tenant', tenantJoinAdminRouter);
router.use('/tenant', tenantLogoRoutes);
router.use('/onboarding/phone-otp', onboardingPhoneOtpRoutes);
router.use('/', onboardingRoutes);
router.use('/tenant', domainTenantRoutes);
router.use('/tenant', domainMemberActionsRoutes);
router.use('/tenant/contacts', domainContactsRoutes);
router.use('/tenant/contact-fields', domainContactFieldsRoutes);
router.use('/member-invitations', domainMemberInvitationsRoutes);
router.use('/public', publicRoutes);
router.use('/chat', chatRoutes);
router.use('/contact-sales', contactSalesRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/leads', leadsRoutes);
router.use('/admin/ai', adminRoutes);
router.use('/admin/users', adminUsersRoutes);
router.use('/payments', paymentsRoutes);
router.use('/partners', partnersRoutes);
router.use('/user', userRoutes);
router.use('/blog', blogRoutes);
router.use('/admin/agent-requests', agentApprovalsRoutes);
router.use('/admin/agents', adminAgentsRoutes);
router.use('/admin/seo', adminSeoRoutes);
router.use('/admin/tenants', adminTenantsRoutes);
router.use('/admin/tenants', adminTenantBrandingRoutes);
router.use('/admin/offers', adminOffersRoutes);
router.use('/admin/business-setup-approvals', adminBusinessSetupApprovalsRoutes);
router.use('/admin/organizations', adminOrganizationsRoutes);
router.use('/seo', seoRoutes);
router.use('/orgs', orgsRoutes);
router.use('/invites', invitesRoutes);
router.use('/push', pushRoutes);
router.use('/offers', offersRoutes);
router.use('/purchase', purchaseRoutes);

export default router;
