// Bilingual search aliases for every /partners org (existing 71 + new 65), 2026-07-09.
// Key = canonical Partner.title (post Homonugus->Humongous rename). Value = alt-language names
// + alternate spellings. Backfilled into Partner.searchTerms by scripts/add-partners.ts.
// Spec: docs/superpowers/specs/2026-07-09-partners-csv-orgs-design.md

export const PARTNER_SEARCH_TERMS: Record<string, string[]> = {
  // ── existing 71 ──
  'Bakers Secret': ['בייקרס סיקרט', 'בקרס סיקט'],
  'Masu': ['מסאו'],
  'Samsung': ['סמסונג'],
  'Kitan': ['כיתן'],
  'Fox Home': ['פוקס הום'],
  'Polgat': ['פולגת'],
  'Adika': ['עדיקה'],
  'הסיירת': ['HaSayeret', 'רשת הסיירת'],
  'SACKS': ['סאקס'],
  'Protein 4 U': ['פרוטאין 4 יו', 'P4U', 'תוספי חלבון'],
  'Minene': ['מיננה'],
  'שילב': ['Shilav'],
  'Ruby Bay': ['רובי ביי'],
  'טרקלין חשמל': ['Traklin Hashmal', 'Traklin Electric'],
  'American Eagle': ['אמריקן איגל'],
  'צעד 4 על 4': ['Tzaad 4x4'],
  'Dynamica': ['דינמיקה'],
  'Rudy Project': ["רודי פרוג'קט"],
  'יער הקופים': ['Monkey Forest', 'Yaar HaKofim'],
  'IBI': ['אי בי אי'],
  'Brisket': ['בריסקט'],
  'Sunglass Hut': ['סאנגלס האט'],
  'Bonita De Mas': ['בוניטה דה מס'],
  'אקסלנס טרייד': ['Excellence Trade'],
  'דקה 90': ['Daka 90', 'הדקה ה-90'],
  'Castro Home': ['קסטרו הום'],
  'ENERGYM': ["אנרג'ים"],
  'Carolina Lamke': ['קרולינה למקה', 'Carolina Lemke'],
  'Fly Box': ['פליי בוקס'],
  'כפר הצוללים': ['Divers Village', 'Kfar HaTzolelim'],
  'Magnus': ['מגנוס'],
  'Rise Up': ['רייזאפ', 'RiseUp'],
  'רמי לוי שיווק השקמה': ['Rami Levy', 'רמי לוי'],
  'Golf Kids': ['גולף קידס'],
  'רפטינג נהר הירדן': ['Jordan River Rafting'],
  'Billabong': ['בילבונג'],
  'Laline': ['ללין'],
  'המשביר לצרכן': ['Hamashbir', 'המשביר'],
  'Foot Locker': ['פוט לוקר'],
  'Home Style': ['הום סטייל', 'HOMESTYLE'],
  'בירה מלכה': ['Malka Beer', 'Malka'],
  'INTIMA': ['אינטימה'],
  'Golf & Co': ['גולף אנד קו'],
  'Boardriders': ['בורדריידרס'],
  'Garmin': ['גארמין'],
  'Mango': ['מנגו'],
  'YANGA': ['יאנגה'],
  'Urbanica': ['אורבניקה', 'URBANIKA'],
  'מיטב טרייד': ['Meitav Trade'],
  'Kiko Milano': ['קיקו מילאנו'],
  'ישראייר': ['Israir'],
  'Spa Plus': ['ספא פלוס', 'ספא+'],
  'נעמן': ['Naaman'],
  'Arie': ['אריה'],
  'ורדינון': ['Vardinon'],
  'Brooks': ['ברוקס'],
  'Budget': ["באדג'ט"],
  'Kernelios': ['קורנליוס', 'מכללת סייבר קורנליוס'],
  'מכון וקסלר': ['Wexler Institute'],
  'IRobot': ['איירובוט', 'iRobot'],
  'Hoodies': ['הודיס'],
  'בית קנדינוף': ['Beit Kandinof', 'מסעדת בית קנדינוף'],
  'Yves Rocher': ['איב רושה'],
  'Afrodita': ['אפרודיטה'],
  'Converse': ['קונברס'],
  'GOOL': ['גול'],
  'Ovali': ['אובלי'],
  'Humongous': ['יומנגס', 'הומונגוס'],
  'קסטרו': ['Castro'],
  'Kenneth Cole': ['קנת קול'],
  'Top Ten': ['טופ טן', 'טופ-טן', 'TOPTEN'],
  // ── new 65 ──
  'Golf': ['גולף', 'גולף אופנה'],
  'אקיפ': ['EQUIP', 'Ekip'],
  'מגנוליה': ['Magnolia'],
  'Quiksilver': ['קוויקסילבר', 'Quick Silver'],
  'Flying Tiger': ['פליינג טייגר', 'Flying Tiger Copenhagen'],
  'Fox': ['פוקס'],
  'Nike': ['נייק'],
  'Terminal X': ['טרמינל איקס'],
  'GALI': ['גלי'],
  'Lee Cooper': ['לי קופר'],
  'Nine West': ['ניין ווסט'],
  'Caterpillar': ['קטרפילר', 'CAT'],
  'Hush Puppies': ['האש פאפיס'],
  'Nautica': ['נאוטיקה'],
  'Timberland': ['טימברלנד'],
  'ALDO': ['אלדו'],
  'Step In': ['סטפ אין'],
  'Gant': ['גנט', 'GANT'],
  'G-Star RAW': ["ג'י סטאר", 'G-Star'],
  'תיקי לברוס': ['Lebros', 'לברוס', 'La Borsa', 'laborsa'],
  'בריז': ['Breeze'],
  'Alxndr': ['אלכסנדר'],
  'אופטיקנה': ['Opticana'],
  'Toys R Us': ['טויס אר אס'],
  'ריקושט': ['Ricochet'],
  'מגה ספורט': ['Mega Sport'],
  'Adidas': ['אדידס'],
  'Diadora': ['דיאדורה'],
  'Reebok': ['ריבוק'],
  'Under Armour': ['אנדר ארמור'],
  'גוד פארם': ['Good Pharm'],
  'iDigital': ['איי דיגיטל', 'I digital'],
  'Keter': ['כתר'],
  'שבילים': ['Shvilim'],
  'H&O': ["אייץ' אנד או"],
  'Sabon': ['סבון'],
  'Columbia': ['קולומביה'],
  'הראל ביטוח': ['Harel Insurance', 'Harel'],
  'MOGEL': ['מוגל'],
  'ארביטראז': ['Arbitrage'],
  'פליישור': ['FlySure', 'Flysure'],
  'וולטי': ['Walty'],
  'מגדל ביטוח': ['Migdal Insurance', 'Migdal'],
  'כלל ביטוח': ['Clal Insurance', 'Clal'],
  'אקזיט וואלי': ['ExitValley', 'Exit Valley'],
  'פמיליביז': ['FamilyBiz'],
  'ימית חנות גלישה': ['Yamit Surf', 'ימית'],
  'קייטשופ': ['KiteShop', 'Kite Shop'],
  'הום פור ספורט': ['Home for Sport'],
  'HOAM SIM': ['הואם סים'],
  'נומה נומה': ['Numa Numa'],
  'צימר נוף הארגמן': ['Nof HaArgaman'],
  'סקיי גלמפינג': ['Sky Glamping'],
  'מכללת יהונתן וולשטיין': ['Wolstein College', 'וולשטיין'],
  'סינמה סיטי': ['Cinema City'],
  'שקם אלקטריק': ['Shekem Electric', 'שקה אלקטריק'],
  'Wolt': ['וולט'],
  'דומינוס פיצה': ["Domino's Pizza", 'Dominos'],
  "ג'פניקה": ['Japanika'],
  'פרעצל': ['Mr Pretzels', 'Pretzel'],
  'פיצה האט': ['Pizza Hut'],
  "בורגראנץ'": ['Burgeranch', 'Burger Ranch'],
  'קרפור': ['Carrefour'],
  'שופרסל': ['Shufersal'],
  'ויקטורי': ['Victory'],
  // ── batch 2: benefits CSV 13.7.26 rows 4-206 (2026-07-15) ──
  'Aerie': ['איירי', 'AERIE'],
  "The Children's Place": ["צ'ילדרנס פלייס", 'Childrens Place'],
  "טבצ'ניק": ['Tabachnik', "טבצ'ניק תכשיטים ויהלומים"],
  'HUGS': ['האגס'],
  'Forest': ['פורסט', 'Forest ציוד טקטי'],
  'IMI Defense': ['איי אם איי דיפנס', 'IMI DEFENSE'],
  'Nimrod & More': ['נמרוד', 'Nimrod'],
  'עגליס': ['Agalis'],
  'מוצצים': ['Motzetzim'],
  'Papaya': ['פפאיה'],
  'Ponpano': ['פונפנו'],
  'Fine Rituals': ['פיין ריטואלס'],
  'The Body Shop': ['בודי שופ', 'Body Shop'],
  'April': ['אפריל'],
  'One Project': ['וואן פרוג\'קט', 'ONE PROJECT'],
  'Desigual': ['דסיגואל'],
  'Emporium': ['אמפוריום'],
  'Replay': ['ריפליי'],
  'Longchamp': ["לונגשאמפ", 'Longchamp Paris'],
  'Brownie': ['בראוני'],
  'Guess': ['גס'],
  'Superdry': ['סופרדריי'],
  'Darlain': ['דארלן', 'darlain'],
  'Ecko Unltd': ['אקו', 'ECKO UNLTD'],
  'TOUS': ['טוס'],
  'Sharagan': ['שרגן'],
  'Easy Spirit': ['איזי ספיריט'],
  'Bimba Y Lola': ['בימבה אי לולה', 'LA BIMBA LOLA'],
  'Picnic': ['פיקניק'],
  'אהבה קטנה': ['Ahava Ktana'],
  'Laster': ['לסטר'],
  'Worker': ['וורקר'],
  'Outsiders': ['אאוטסיידרס'],
  'Show Off': ['שואו אוף', 'SHOW/OFF'],
  'תיק התיקים': ['Tik HaTikim'],
  'Steve Madden': ['סטיב מאדן'],
  'Havaianas': ['הוויאנס'],
  'Big Shop': ['ביג שופ'],
  'WINTAX': ['ווינטקס'],
  'GOOLA': ['גולה'],
  'Freedive': ['פרידייב'],
  'סנפיר': ['Snapir', 'סנפיר מוניטין צלילה 2000'],
  '3DSTEP': ['תלת מימד סטפ', '3D STEP'],
  'SAYSKY': ['סייסקיי'],
  'Horizon': ['הורייזון', 'מועדון הגלישה HORIZON'],
  'בשבילי התבור': ['Bishvilei HaTavor'],
  'קומדי בר': ['Comedy Bar'],
  'מנווטים קדימה': ['Menavtim Kadima'],
  'ארץ קיר': ['Eretz Kir'],
  'צומת ספרים': ['Tzomet Sfarim'],
  '2JUMP': ['טו ג\'אמפ'],
  'Albume': ['אלבומי'],
  'Red Sea Aqua Sport': ['אקווה ספורט', 'RED SEA AQUA-SPORT'],
  'PetEat': ['פטיט', 'peteat'],
  'ישיבת אורות המקודש': ['Orot HaMekudash'],
  'מדעטק': ['Madatech'],
  'Hot Cinema': ['הוט סינמה'],
  'פארק קרסו למדע': ['Carasso Science Park', 'קרסו'],
  'ZMRM': ['זמרם', 'ZMRM.co.il'],
  'ShareSpa': ['שר ספא'],
  'האקדמיה לפיננסים': ['Finance Academy', 'BDO Academy'],
  'Workits': ['וורקיטס'],
  'סופר פארם': ['Super-Pharm', 'Super Pharm'],
  'ACE': ['אייס'],
  'מחסני חשמל': ['Machsanei Hashmal'],
  'הסטוק': ['HaStock', 'Stock'],
  'הום סנטר': ['Home Center'],
  'Arcosteel': ['ארקוסטיל', 'ARCOSTEEL Kitchen'],
  'אלקטריק דיפו': ['Electric Depo', 'Electric Depot'],
};
